### ISSUE TITLE
Add Kafka to Nextjs so we can get rid of the separate WSS

### ISSUE THREAD

**Issue by Brett-Mulder** [fuas-dverse/DVerse-UI#11]
# Description
Now we have the Frontend connected a backend that is a Websocket Server, that websocker server is connected to the message bus. So all the messages needs to get throught the websocker server. This issue is about removing the Websocker Server and add the Kafka logic in here. Because NextJS can have a backend on its own.

# Tasks
- [ ] Find a way to connect Kafka to the frontend
- [ ] Add kafka to frontend
- [ ] Start consuming messages
- [ ] Filter the messages based on ID that is in the header
- [ ] SHow message to the user

# DOD
- The frontend is connected to the kafka message bus and recieved and show messages
