### ISSUE TITLE
Deploy UI to Vercel

### ISSUE THREAD

**Issue by RenoMuijsenberg** [fuas-dverse/DVerse-UI#7]
# Description 
We want to deploy our application to Vercel in order to make it accessible for everyone. Currently we are using Docker Compose to host our Keycloak, so this needs to be changed to a cloud based version.

# Tasks
- [x] Setup new project in vercel
- [x] Create cloud based version for keycloak
- [x] Connect NextJS to keycloak
- [x] Add environment variables for production
- [x] Add safety using the Firewall option in vercel

# DOD
- The app is running and available for everyone
- Everyone can signup using keycloak
